import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b">
          <div className="max-w-5xl mx-auto px-4 h-12 flex items-center justify-between">
            <a href="/" className="font-semibold">App</a>
            <nav className="space-x-4 text-sm">
              <a href="/dashboard" className="underline">Dashboard</a>
              <a href="/login" className="underline">Login</a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
